language: c

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install moonscript
  - sudo luarocks install luacrypto
  - sudo luarocks install luaposix
  - sudo luarocks install https://raw.githubusercontent.com/leafo/lua-date/master/date-dev-1.rockspec
  - sudo luarocks install busted
  - sudo luarocks make

script: luajit-2.0.0-beta9 $(cat $(which busted) | grep -Po '[^'"'"']*?bin/busted')
